I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label take_rune is defined twice, at File "game/act_three_b1.rpy", line 23:
            label take_rune:
and File "game/act_three_b3.rpy", line 22:
            label take_rune:


Ren'Py Version: Ren'Py 8.2.0.24012702
Mon Mar 11 23:20:09 2024
